---

stages:
- build
- publish

test and build dists:
  image: containers.dev.maio.me/sjohnson/containers/poetry:latest
  stage: build
  tags:
  - amd64
  script:
  - apk add --no-cache build-base git python3-dev
  - poetry develop
  - poetry run pytest --verbose --junit-xml=pytest-junit.xml --cov-report=html:htmlcov
  - poetry build
  coverage: '/TOTAL.+?(\d+)%/'
  artifacts:
    name: "$CI_JOB_NAME-$CI_COMMIT_REF_NAME"
    paths:
    - dist/
    - htmlcov/
    reports:
      junit: pytest-junit.xml

pages:
  image: containers.dev.maio.me/sjohnson/containers/alpine:latest
  tags:
  - amd64
  stage: publish
  dependencies:
  - test and build dists
  script:
  - mkdir public
  - mv htmlcov public/coverage
  artifacts:
    paths:
    - public
